### ISSUE TITLE
MW vypocitat RDkitem ze SMILES

### ISSUE THREAD

**Issue by KarelBerka** [MolMeDB/MolMeDB#30]
MW se aktualne natahuje z PubChemu, ze? (odhaduju to na zaklade toho, ze u pojmenovanych latek je mozne MW najit, ale u generickych MM ne) 

RDkit by to ale mel byt schopen spocitat u vsech, kde mame SMILES.

**Comment by jurja00** [comment]
Je to nachystané už dlouho, jen jsem to ještě neměl čas spustit. Bude to dělat ten cron, který bude delat i validace. Zkusím se k tomu tento víkend dostat a rozjet to. Chybí mi právě dodělat to rozhraní pro validaci možných duplicit.

**Comment by KarelBerka** [comment]
Super

**Comment by KarelBerka** [comment]
duplicate issue k RDKIT one
