### ISSUE TITLE
MDCG male obsazeni 

### ISSUE THREAD

**Issue by KarelBerka** [MolMeDB/MolMeDB#31]
Kontrolou Noe zjistil, ze MDCG (9791) latek ma jen 66% pokryti logPerm, coz je divne, protoze to je dataset z MARTINI, ktery byl jen o permeabilite

**Comment by MrYodas** [comment]
Tam bude jeste vice chyb ... nazvy molekul byly automaticky generovane a u vetsiny latek nedava smysl (jmena typu MM01553 atd ...) ... naboj jsme urcili u 2185 molekul ... netusim, kde se tam vzal ten zbytek ..

a nelze to ani zkontrolovat, protoze pri otevreni datasetu mi pada stranka na tomto: 
![Screenshot 2020-09-14 at 11 24 05](https://user-images.githubusercontent.com/46314782/93068473-cdf53c00-f67c-11ea-8757-91ab20e88235.png)

**Comment by KarelBerka** [comment]
Pak je třeba ty molekuly z metody MDCG bez dalších hodnot z databáze smazat.

**Comment by jurja00** [comment]
6534 interakcí (MDCG) má LogPerm
3257 interakcí je bez jakékoliv hodnoty => Mažu je

**Comment by KarelBerka** [comment]
Super
