### ISSUE TITLE
nesmyslne hodnoty CCM18/DOPC - k umazani 

### ISSUE THREAD

**Issue by KarelBerka** [MolMeDB/MolMeDB#32]
Ahoj, 
slo by nejak efektivne smazat hodnoty logK pro CCM18/DOPC data pro nasledujici latky v MolMeDB? Jsou nesmyslne velka

MM00913
MM00880
MM00852
MM00937
MM00581
MM00790
MM01010
MM00340
MM00577
MM00088
MM00300
MM00254
MM00554
MM00585
MM00416
MM00338
MM00504
MM00578
MM00883
MM00857
MM00674
MM00903
MM00580
MM00489
MM00457
MM00287
MM00472
MM01008
MM00503
MM00280
MM00385
MM01028
MM00751
MM01027
MM00478
MM01014
MM00474
MM00484
MM00853
MM00480
MM00310
MM00552
MM00003
MM00510
MM00483
MM00589
MM01019
MM00353
MM00931
MM00453
MM00561
MM00997
MM00894
MM00454
MM00746
MM00475
MM00588
MM00527
MM00278
MM00863
MM00019
MM00090
MM00488
MM00507
MM00644
MM00557
MM00797
MM00656
MM00587
MM00560
MM00520
MM00311
MM00519
MM00455
MM00456
MM00045
MM00002
MM00583
MM00895
MM00576
MM00584
MM00521
MM00860
MM00092
MM00357
MM00429
MM00481
MM00085
MM00774
MM00476
MM00861
MM00672
MM00960
MM00992
MM00275
MM00586
MM00095
MM00027
MM00005
MM00946
MM00591
MM00477
MM00197
MM00518
MM00006
MM00114
MM00559
MM00791
MM00289
MM00954
MM00339
MM00526
MM00007
MM01013
MM00985
MM00662
MM00430
MM00010
MM00279
MM00881
MM00590
MM00008
MM00517
MM00350
MM00367
MM00367
MM00367
MM01053
MM01031
MM00893
MM00912
MM00023
MM00028
MM00011
MM00897
MM00732
MM00957
MM00053
MM00793
MM00013
MM00479
MM00384
MM00762
MM00359
MM00831
MM00529
MM00956
MM00562
MM00004
MM00925
MM00025
MM00661
MM01021
MM00764
MM00525
MM00854
MM00434
MM00140
MM00830
MM00418
MM00285
MM00987
MM00312
MM00556
MM01011
MM00984
MM00021
MM00882
MM00660
MM00487
MM00733
MM00673
MM00731
MM00486
MM00219
MM00047
MM00986
MM00855
MM00933
MM00582
MM00858
MM00391
MM00859
MM00201
MM01283
MM00936
MM00524
MM00768
MM00844
MM00026
MM00935
MM00284
MM00794
MM00924
MM00355
MM00024
MM00225
MM00020
MM00669
MM00012
MM00415
MM00361

**Comment by jurja00** [comment]
Hotovo
