### ISSUE TITLE
Navigator page for methods

### ISSUE THREAD

**Issue by KarelBerka** [MolMeDB/MolMeDB#39]
Prepare Navigator page for methods similarly as for membranes - 
Major division: 
- Experimental 
- Computed
- Simulated

**Comment by KarelBerka** [comment]
Minor division - Experimental 
- Partitioning - EHDP, EPDMS, ESPME, EPHT
- Penetration - EBLM, EPAM, ECACO, ELFA, EFDC, EPS, EUC, EDC, EBAMP, (E)NMRD, (E)FALUV, (E)GUV-CCD, (E)MA-GUV, (E)DC-DMR, 
- Fluorescence - ELFA, ECFM, ESSM, EPFQ, ETRFES, EFCS, (E)FALUV, 

(E) denotes that such is experimental method and I will change them to have such names for easy recognition

**Comment by KarelBerka** [comment]
Minor division - Computed
- QM-based - CCM15, CCM18
- mechanistic - CPMM, CPapp, 
- QSAR - CQSAR, CXLP3

CQSAR => I suggest to rename it to specific QSAR methods, such as VolSurf in the description of the method

**Comment by KarelBerka** [comment]
Minor division - Simulated
- atomistic MD - MDUSA4A9, MDUSC36, MDCH27, MDSLA99SB, MDABFC36
- united atoms MD - MDUSBG56, MDUSG43A1S3, MDG43A1S3, MDG87
- coarse grain MD - MMAR, MDCG
- hybrid - MDDMM, MDD, MDSmC36 

MDD requires better description 
MDUSG43A1S3 is similar to MDG43A1S3

**Comment by jurja00** [comment]
Resolved by #71
